# Generated by Django 4.2.6 on 2023-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showsession",
            name="show_time",
            field=models.DateTimeField(null=True),
        ),
    ]
