# Generated by Django 4.2.6 on 2023-10-13 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row",)},
        ),
    ]
