# Generated by Django 4.2.6 on 2023-10-09 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_alter_reservation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 9, 22, 11, 14, 874136)
            ),
        ),
    ]
