# Generated by Django 4.2.6 on 2023-10-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_alter_planetariumdome_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showsession",
            name="astronomy_show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows_session",
                to="planetarium.astronomyshow",
            ),
        ),
    ]
