# Generated by Django 4.2.6 on 2023-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0005_alter_reservation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
